test:ubuntu16.10-gcc:
  image: ubuntu:rolling
  before_script: 
    - apt update
    - apt -y install build-essential cmake
    - apt -y install libopencv-dev libboost-python-dev libboost-test-dev
    - apt -y install python3-dev python3-numpy
  script: 
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - make test

test:arch-gcc:
  image: pritunl/archlinux
  before_script: 
    - pacman -S --noconfirm base-devel cmake
    - pacman -S --noconfirm opencv boost python python-numpy
  script: 
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - make test

test:arch-clang:
  image: pritunl/archlinux
  before_script:
    - pacman -S --noconfirm base-devel cmake clang
    - pacman -S --noconfirm opencv boost python python-numpy
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_CXX_COMPILER=clang++ ..
    - make
    - make test
